"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { ShedGuide, ShedGuideItem } from "../../../lib/guides/shed";
import { startShedLookup } from "./actions";
function Source({ item }: { item: ShedGuideItem }) { const citation=item.citations[0]; if(!citation)return null; const detail=`${citation.sourceTitle}, ${citation.sectionIdentifier}`; return <p className="guide-source">{citation.sourceUrl&&<a href={citation.sourceUrl} target="_blank" rel="noreferrer" aria-label={`View source, ${detail}`} title={detail}>Source ↗</a>}</p>; }
function Cards({items}:{items:ShedGuideItem[]}) { return <section className="guide-highlights" aria-labelledby="shed-rules"><h2 id="shed-rules">Your shed rules</h2><div className="highlight-grid">{items.map(item=><article className="highlight-item" key={item.key}><h3>{item.title}</h3><p className="highlight-answer">{item.answer}</p>{item.qualification&&<p className="highlight-qualification">{item.qualification}</p>}<Source item={item}/></article>)}</div></section>; }
function Situations({items}:{items:ShedGuideItem[]}) { return <section className="specific-situations"><h2>Specific situations</h2><div>{items.map(item=><article className="specific-situation" key={item.key}><h3>{item.title}</h3><p>{item.answer}</p><Source item={item}/></article>)}</div></section>; }
const residentAddress=(value:string)=>value.toLowerCase().replace(/\b\p{L}/gu,letter=>letter.toUpperCase());
export function ShedWorkflow(){
 const router=useRouter();
 const [address,setAddress]=useState(""); const [confirmed,setConfirmed]=useState<string|null>(null); const [guide,setGuide]=useState<ShedGuide|null>(null); const [stage,setStage]=useState<"address"|"project"|"guide">("address"); const [error,setError]=useState<string|null>(null); const [pending,startTransition]=useTransition();
 const lookup=()=>startTransition(async()=>{try{const found=await startShedLookup(address);if(!found){setError("This address isn’t in our limited Clearwater pilot area yet. We did not evaluate it.");return;}if(found.status==="blocked"){setError(found.reason==="outside"?`THIS PROPERTY IS OUTSIDE CLEARWATER CITY LIMITS · Jurisdiction · ${found.jurisdictionName??"Outside Clearwater"}. Clearwater's property rules don't apply to this address.`:"WE COULDN'T CONFIRM THIS PROPERTY'S JURISDICTION. Groundrule won't apply Clearwater rules until it can be confirmed.");return;}setConfirmed(found.displayAddress);setGuide(found.guide);setStage("project");setError(null);}catch{setError("We couldn’t look up that address right now. Please try again later.");}}); const reset=()=>{setAddress("");setConfirmed(null);setGuide(null);setStage("address");setError(null);};
 return <main className="workflow-shell"><header className="workflow-brand">GROUNDRULE <span>Clearwater, Florida</span></header>
 {stage==="address"&&<section className="address-panel"><p className="eyebrow">Clearwater property guide</p><h1>Enter your property address</h1><p className="workflow-copy">Guidance based on current City rules and property data.</p><div className="address-form"><input aria-label="Property address" placeholder="1950 Drew Plz" value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>e.key==="Enter"&&address.trim()&&lookup()}/><button disabled={pending||!address.trim()} onClick={lookup}>{pending?"Looking…":"Continue"}</button></div>{error&&<p role="alert" className="warning">{error}</p>}</section>}
 {stage==="project"&&confirmed&&<section className="address-panel"><p className="found">✓ Property found</p><h1 className="address-heading">{residentAddress(confirmed)}<small>Clearwater, FL</small></h1><div className="project-choice"><h2>What do you need help with?</h2><div className="project-grid"><button onClick={()=>router.push("/clearwater/fence")}>Fence <span>→</span></button><button onClick={()=>setStage("guide")}>Shed <span>→</span></button></div></div></section>}
 {stage==="guide"&&guide&&confirmed&&<article className="guide"><h1>{residentAddress(confirmed)}</h1><aside className="property-context" aria-label="Property facts used"><ul>{guide.propertyContext.map(fact=><li key={fact}>{fact}</li>)}</ul></aside><p className="guide-intro">Guidance only · Based on current Clearwater rules and property data · Not a permit or City approval</p><Cards items={guide.highlights}/><Situations items={guide.specificSituations}/><button className="new-search" onClick={reset}>← New search</button></article>}
 </main>;
}
