"use client";
import { startPoolLookup } from "./actions";
const permitUrl="https://www.myclearwater.com/Business-Development/Permitting/05-Residential-In-Ground-PoolsSpas-Enclosures-Application-Checklists";
import { ClearwaterResidentShell } from "../resident-shell";

export function PoolWorkflow({initialAddress="",openProject=false}:{initialAddress?:string;openProject?:boolean}) {
 return <ClearwaterResidentShell activeGuide="pool" initialAddress={initialAddress} openProject={openProject} lookup={startPoolLookup} validateGuide={guide=>!!guide.setbacks.length&&!!guide.measurement}>
 {(guide,openGuide)=><article className="guide"><h1>Pool guidance</h1><aside className="property-context" aria-label="Property facts used"><ul>{guide.propertyContext.map(x=><li key={x}>{x}</li>)}</ul></aside><p className="guide-intro">Ordinary detached-dwelling pool guidance · Not a permit or review of your plans</p><section className="guide-highlights setback-highlights"><header><h2>Pool setbacks</h2><p>Minimum distance from the corresponding property line.</p></header><div className="highlight-grid">{guide.setbacks.map(x=><article className="highlight-item" key={x.key}><h3>{x.title}</h3><p className="highlight-answer">{x.answer}</p><p className="highlight-qualification">minimum</p></article>)}</div></section>{guide.measurement&&<section className="pool-measurement"><h2>{guide.measurement.title}</h2><p>{guide.measurement.answer}</p><p>Groundrule has not measured your property or reviewed proposed geometry.</p></section>}<section className="specific-situations"><h2>Specific situations</h2><div>{guide.situations.map(x=><article className="specific-situation" key={x.key}><h3>{x.title}</h3><p>{x.answer}</p>{x.key==="situation.barrier"&&<button onClick={()=>openGuide("fence")}>Open Fence Guide →</button>}</article>)}</div><aside className="related-guides"><h3>Impervious surface also matters</h3><p>The City checklist requires an ISR worksheet. Groundrule can show the applicable maximum, but does not calculate current or remaining capacity.</p><button onClick={()=>openGuide("impervious-surface-ratio")}>Open Impervious Surface Ratio Guide →</button></aside></section>{guide.permit&&<section className="guide-section"><h2>Next step</h2><p>{guide.permit.answer}</p><a className="primary-link" href={permitUrl} target="_blank" rel="noreferrer">View Clearwater pool permit checklist →</a></section>}</article>}
 </ClearwaterResidentShell>;
}
