"use client";
import type { SetbackGuideItem,SetbacksGuide } from "../../../lib/guides/setbacks";
import { startSetbacksLookup } from "./actions";
const relatedGuides = [{key:"fence",label:"Fence"},{key:"shed",label:"Shed"}] as const;
function SetbackCards({items,onOpenGuide}:{items:SetbackGuideItem[];onOpenGuide:(key:(typeof relatedGuides)[number]["key"])=>void}){return <section className="guide-highlights setback-highlights" aria-labelledby="setback-rules"><header><h2 id="setback-rules">Standard home setbacks</h2><p>Minimum distance from your property line to your home.</p></header><div className="highlight-grid">{items.map(item=><article className="highlight-item" key={item.title}><h3>{item.title}</h3><p className="highlight-answer">{item.answer}</p><p className="highlight-qualification">{item.qualification}</p></article>)}</div><aside className="related-guides" aria-labelledby="related-guides-heading"><h3 id="related-guides-heading">Building something else?</h3><p>Certain improvements have different setback rules.</p><div className="related-guide-links">{relatedGuides.map(guide=><button key={guide.key} onClick={()=>onOpenGuide(guide.key)}>{guide.label} <span aria-hidden="true">→</span></button>)}</div><p className="related-guides-escalation">Something else? Contact Clearwater.</p></aside></section>}
function Situations({items}:{items:SetbackGuideItem[]}){return <section className="specific-situations"><h2>Specific situations</h2><div>{items.map(item=><article className="specific-situation" key={item.key}><h3>{item.title}</h3><p>{item.answer}</p></article>)}</div></section>}
function TrustCue({guide}:{guide:SetbacksGuide}){const codeUrl=[...guide.setbacks,...guide.specificSituations].flatMap(item=>item.citations).find(citation=>citation.sourceUrl)?.sourceUrl;if(!codeUrl)return null;return <aside className="setbacks-trust" aria-label="Clearwater code source"><p><strong>Based on Clearwater’s current development standards</strong></p><p>Groundrule uses official City of Clearwater codes and property data to generate this guidance.</p><a href={codeUrl} target="_blank" rel="noreferrer">View Clearwater codes <span aria-hidden="true">→</span></a></aside>}
import { ClearwaterResidentShell } from "../resident-shell";

export function SetbacksWorkflow({initialAddress="",openProject=false}:{initialAddress?:string;openProject?:boolean}) {
 return <ClearwaterResidentShell activeGuide="setbacks" initialAddress={initialAddress} openProject={openProject} lookup={startSetbacksLookup}>
 {(guide,openGuide)=><article className="guide"><h1>Standard home setbacks</h1><aside className="property-context" aria-label="Property facts used"><ul>{guide.propertyContext.map(fact=><li key={fact}>{fact}</li>)}</ul></aside><p className="guide-intro">Standard detached-dwelling guidance · Based on current Clearwater rules and property data · Not a permit or City approval</p><SetbackCards items={guide.setbacks} onOpenGuide={openGuide}/><Situations items={guide.specificSituations}/><TrustCue guide={guide}/></article>}
 </ClearwaterResidentShell>;
}
