"use client";
import { useEffect,useRef,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import type { SetbackGuideItem,SetbacksGuide } from "../../../lib/guides/setbacks";
import { ProjectHandoffStatus } from "../project-handoff";
import { startSetbacksLookup } from "./actions";
function Source({item}:{item:SetbackGuideItem}){const citation=item.citations[0];if(!citation)return null;const detail=`${citation.sourceTitle}, ${citation.sectionIdentifier}`;return <p className="guide-source">{citation.sourceUrl&&<a href={citation.sourceUrl} target="_blank" rel="noreferrer" aria-label={`View source, ${detail}`} title={detail}>Source ↗</a>}</p>}
const relatedGuides = [{key:"fence",label:"Fence"},{key:"shed",label:"Shed"}] as const;
function SetbackCards({items,onOpenGuide}:{items:SetbackGuideItem[];onOpenGuide:(key:(typeof relatedGuides)[number]["key"])=>void}){return <section className="guide-highlights setback-highlights" aria-labelledby="setback-rules"><header><h2 id="setback-rules">Standard home setbacks</h2><p>Minimum distance from your property line to your home.</p></header><div className="highlight-grid">{items.map(item=><article className="highlight-item" key={item.title}><h3>{item.title}</h3><p className="highlight-answer">{item.answer}</p><p className="highlight-qualification">{item.qualification}</p><Source item={item}/></article>)}</div><aside className="related-guides" aria-labelledby="related-guides-heading"><h3 id="related-guides-heading">Building something else?</h3><p>Certain improvements have different setback rules.</p><div className="related-guide-links">{relatedGuides.map(guide=><button key={guide.key} onClick={()=>onOpenGuide(guide.key)}>{guide.label} <span aria-hidden="true">→</span></button>)}</div><p className="related-guides-escalation">Something else? Contact Clearwater.</p></aside></section>}
function Situations({items}:{items:SetbackGuideItem[]}){return <section className="specific-situations"><h2>Specific situations</h2><div>{items.map(item=><article className="specific-situation" key={item.key}><h3>{item.title}</h3><p>{item.answer}</p><Source item={item}/></article>)}</div></section>}
const residentAddress=(value:string)=>value.toLowerCase().replace(/\b\p{L}/gu,letter=>letter.toUpperCase());
export function SetbacksWorkflow({initialAddress="",openProject=false}:{initialAddress?:string;openProject?:boolean}){const router=useRouter();const isProjectHandoff=openProject&&initialAddress.trim().length>0;const[address,setAddress]=useState("");const[confirmed,setConfirmed]=useState<string|null>(null);const[guide,setGuide]=useState<SetbacksGuide|null>(null);const[stage,setStage]=useState<"address"|"handoff"|"project"|"guide">(isProjectHandoff?"handoff":"address");const[error,setError]=useState<string|null>(null);const[pending,startTransition]=useTransition();
const lookup=(requestedAddress=address,showGuide=false)=>startTransition(async()=>{try{const found=await startSetbacksLookup(requestedAddress);if(!found){setStage(showGuide?"handoff":"address");setError("This address isn’t in our limited Clearwater pilot area yet. We did not evaluate it.");return}if(found.status==="blocked"){setStage(showGuide?"handoff":"address");setError(found.reason==="outside"?`THIS PROPERTY IS OUTSIDE CLEARWATER CITY LIMITS · Jurisdiction · ${found.jurisdictionName??"Outside Clearwater"}. Clearwater's property rules don't apply to this address.`:"WE COULDN'T CONFIRM THIS PROPERTY'S JURISDICTION. Groundrule won't apply Clearwater rules until it can be confirmed.");return}if(!found.guide.setbacks.length){setStage(showGuide?"handoff":"project");setError("We couldn’t establish standard dwelling setbacks for this property’s zoning. Groundrule did not substitute generic values.");return}setAddress(requestedAddress);setConfirmed(found.displayAddress);setGuide(found.guide);setStage(showGuide?"guide":"project");setError(null)}catch{setStage(showGuide?"handoff":"address");setError("We couldn’t look up that address right now. Please try again later.")}});
const opened=useRef(false);useEffect(()=>{if(openProject&&initialAddress&&!opened.current){opened.current=true;lookup(initialAddress,true)}},[initialAddress,openProject]); // eslint-disable-line react-hooks/exhaustive-deps
const reset=()=>{setAddress("");setConfirmed(null);setGuide(null);setStage("address");setError(null)};
return <main className="workflow-shell"><header className="workflow-brand">GROUNDRULE <span>Clearwater, Florida</span></header>{stage==="handoff"&&<ProjectHandoffStatus error={error} onNewSearch={reset}/>} {stage==="address"&&<section className="address-panel"><p className="eyebrow">Clearwater property guide</p><h1>Enter your property address</h1><p className="workflow-copy">Guidance based on current City rules and property data.</p><div className="address-form"><input aria-label="Property address" placeholder="1950 Drew Plz" value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>e.key==="Enter"&&address.trim()&&lookup()}/><button disabled={pending||!address.trim()} onClick={()=>lookup()}>{pending?"Looking…":"Continue"}</button></div>{error&&<p role="alert" className="warning">{error}</p>}</section>}{stage==="project"&&confirmed&&<section className="address-panel"><p className="found">✓ Property found</p><h1 className="address-heading">{residentAddress(confirmed)}<small>Clearwater, FL</small></h1><div className="project-choice"><h2>What do you need help with?</h2><div className="project-grid"><button onClick={()=>router.push(`/clearwater/fence?address=${encodeURIComponent(confirmed)}&project=fence`)}>Fence <span>→</span></button><button onClick={()=>router.push(`/clearwater/shed?address=${encodeURIComponent(confirmed)}&project=shed`)}>Shed <span>→</span></button><button onClick={()=>setStage("guide")}>Setbacks <span>→</span></button></div></div></section>}{stage==="guide"&&guide&&confirmed&&<article className="guide"><h1>{residentAddress(confirmed)}</h1><aside className="property-context" aria-label="Property facts used"><ul>{guide.propertyContext.map(fact=><li key={fact}>{fact}</li>)}</ul></aside><p className="guide-intro">Standard detached-dwelling guidance · Based on current Clearwater rules and property data · Not a permit or City approval</p><SetbackCards items={guide.setbacks} onOpenGuide={project=>router.push(`/clearwater/${project}?address=${encodeURIComponent(confirmed)}&project=${project}`)}/><Situations items={guide.specificSituations}/><button className="new-search" onClick={reset}>← New search</button></article>}</main>}
