"use client";
import {useEffect,useRef,useState,useTransition} from "react";import {useRouter} from "next/navigation";
import type {ImperviousSurfaceRatioGuide} from "../../../lib/guides/impervious-surface-ratio";import {ProjectHandoffStatus} from "../project-handoff";import {startImperviousSurfaceRatioLookup} from "./actions";
const residentAddress=(value:string)=>value.toLowerCase().replace(/\b\p{L}/gu,letter=>letter.toUpperCase());
function Source({guide}:{guide:ImperviousSurfaceRatioGuide}){const c=guide.citations[0];if(!c)return null;const detail=`${c.sourceTitle}, ${c.sectionIdentifier}`;return <p className="guide-source"><a href={c.sourceUrl??undefined} target="_blank" rel="noreferrer" title={detail}>Source ↗</a></p>}
export function ImperviousSurfaceRatioWorkflow({initialAddress="",openProject=false}:{initialAddress?:string;openProject?:boolean}){const router=useRouter();const handoff=openProject&&!!initialAddress.trim();const[address,setAddress]=useState("");const[confirmed,setConfirmed]=useState<string|null>(null);const[guide,setGuide]=useState<ImperviousSurfaceRatioGuide|null>(null);const[stage,setStage]=useState<"address"|"handoff"|"project"|"guide">(handoff?"handoff":"address");const[error,setError]=useState<string|null>(null);const[pending,startTransition]=useTransition();
const lookup=(requested=address,show=false)=>startTransition(async()=>{try{const found=await startImperviousSurfaceRatioLookup(requested);if(!found){setStage(show?"handoff":"address");setError("This address isn’t in our limited Clearwater pilot area yet. We did not evaluate it.");return}if(found.status==="blocked"){setStage(show?"handoff":"address");setError(found.reason==="outside"?"This property is outside Clearwater city limits. Clearwater’s rules were not applied.":"We couldn’t confirm this property’s jurisdiction, so Clearwater’s rules were not applied.");return}setAddress(requested);setConfirmed(found.displayAddress);setGuide(found.guide);setStage(show?"guide":"project");setError(null)}catch{setStage(show?"handoff":"address");setError("We couldn’t look up that address right now. Please try again later.")}});
const opened=useRef(false);useEffect(()=>{if(openProject&&initialAddress&&!opened.current){opened.current=true;lookup(initialAddress,true)}},[initialAddress,openProject]); // eslint-disable-line react-hooks/exhaustive-deps
const reset=()=>{setAddress("");setConfirmed(null);setGuide(null);setStage("address");setError(null)};
const go=(key:string)=>router.push(`/clearwater/${key}?address=${encodeURIComponent(confirmed!)}&project=${key}`);
return <main className="workflow-shell"><header className="workflow-brand">GROUNDRULE <span>Clearwater, Florida</span></header>{stage==="handoff"&&<ProjectHandoffStatus error={error} onNewSearch={reset}/>} {stage==="address"&&<section className="address-panel"><p className="eyebrow">Clearwater property guide</p><h1>Enter your property address</h1><p className="workflow-copy">Guidance based on current City rules and property data.</p><div className="address-form"><input aria-label="Property address" placeholder="1950 Drew Plz" value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>e.key==="Enter"&&address.trim()&&lookup()}/><button disabled={pending||!address.trim()} onClick={()=>lookup()}>{pending?"Looking…":"Continue"}</button></div>{error&&<p role="alert" className="warning">{error}</p>}</section>}{stage==="project"&&confirmed&&<section className="address-panel"><p className="found">✓ Property found</p><h1 className="address-heading">{residentAddress(confirmed)}<small>Clearwater, FL</small></h1><div className="project-choice"><h2>What do you need help with?</h2><div className="project-grid">{[["fence","Fence"],["shed","Shed"],["setbacks","Setbacks"],["short-term-rental","Short-term rental"]].map(([key,label])=><button key={key} onClick={()=>go(key)}>{label} <span>→</span></button>)}<button onClick={()=>setStage("guide")}>Impervious surface ratio <span>→</span></button></div></div></section>}{stage==="guide"&&guide&&confirmed&&<article className="guide"><h1>{residentAddress(confirmed)}</h1><aside className="property-context" aria-label="Property facts used"><ul>{guide.propertyContext.map(f=><li key={f}>{f}</li>)}</ul></aside><section className={`isr-answer isr-answer-${guide.status}`}><p className="eyebrow">Impervious surface ratio</p><h2>{guide.heading}</h2>{guide.maximumPercent!==null&&<p className="isr-value">{guide.maximumPercent}%</p>}<p>{guide.explanation}</p><p className="isr-scope">{guide.scopeNote}</p><Source guide={guide}/></section><button className="new-search" onClick={reset}>← New search</button></article>}</main>}
