-- Clearwater Short-term Rental V1. Forward-only, limited to the deterministic LMDR result.
begin;
insert into public.project_types(key,label,description) values ('short_term_rental','Short-term rental','Property-specific overnight-accommodation land-use guidance') on conflict(key) do nothing;
insert into public.rule_sets(jurisdiction_id,project_type_id,key,title,scope_description,coverage_status,research_status,effective_from,verified_at,published_at,known_gaps)
select j.id,p.id,'clearwater_short_term_rental_v1','Clearwater short-term rental eligibility','Deterministic ordinary result for Clearwater LMDR parcels.','limited','verified',date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',timestamptz '2026-08-27 00:00:00+00','["Other zoning districts require additional parcel facts and approval-path analysis", "lawful nonconforming overnight accommodations"]'::jsonb from public.jurisdictions j,public.project_types p where j.slug='clearwater-fl' and p.key='short_term_rental' on conflict(jurisdiction_id,project_type_id,key) do nothing;
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,v.locator,v.display,v.title,v.excerpt,'https://library.municode.com/fl/clearwater/codes/community_development_code',timestamptz '2026-08-27 00:00:00+00',v.notes from public.regulatory_sources s cross join (values
('8-102-overnight-accommodations','§ 8-102','Overnight accommodations definition','Overnight accommodations are facilities offered or advertised for occupancy for less than 31 days or one calendar month, whichever is less.','Controlling duration and use classification.'),
('2-202-204-lmdr-uses','§§ 2-202–2-204','LMDR permitted uses','The exhaustive LMDR Level One and Level Two use tables do not include overnight accommodations.','Read with § 8-102 definition and § 8-102 permitted-use definition.')
) v(locator,display,title,excerpt,notes) where s.title='Clearwater Community Development Code' on conflict(regulatory_source_id,locator) do nothing;
insert into public.rules(rule_set_id,key,title,group_key) select rs.id,'eligibility.lmdr_prohibition','LMDR overnight-accommodation prohibition','eligibility' from public.rule_sets rs where rs.key='clearwater_short_term_rental_v1' on conflict(rule_set_id,key) do nothing;
insert into public.rule_versions(rule_id,version_number,condition,evaluation_mode,research_status,lifecycle_status,research_confidence,summary,explanation_template,research_notes,effective_from,verified_at,published_at,schema_version)
select r.id,1,'{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'deterministic','verified','withdrawn','high','Overnight accommodations are not a permitted use in the LMDR District.','Short-term rentals are not permitted in the LMDR zoning district.','The use is defined by duration; LMDR tables omit it while other districts expressly list it.',date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',null,1 from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_short_term_rental_v1' and r.key='eligibility.lmdr_prohibition' on conflict(rule_id,version_number) do nothing;
insert into public.rule_outcomes(rule_version_id,sequence,outcome_type,subject_input_id,parameters,severity,message_template)
select rv.id,1,'prohibition',null,'{"rental_term":"less_than_31_days_or_one_calendar_month_whichever_is_less"}'::jsonb,'requirement','Your property is zoned LMDR. Short-term rentals are not permitted in this zoning district.' from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_short_term_rental_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,sequence) do nothing;
insert into public.rule_version_inputs(rule_version_id,input_definition_id,role,authority_requirement,notes)
select rv.id,d.id,'applicability','authoritative','Trusted zoning selects the supported LMDR profile.' from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id join public.input_definitions d on d.key='property.zoning_district' where rs.key='clearwater_short_term_rental_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,input_definition_id,role) do nothing;
insert into public.rule_citations(rule_version_id,source_provision_id,citation_role,pinpoint_note,sequence)
select rv.id,sp.id,v.role,v.note,v.sequence from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id cross join (values ('2-202-204-lmdr-uses','primary','LMDR use tables.',1),('8-102-overnight-accommodations','definition','Duration-based definition.',2)) v(locator,role,note,sequence) join public.source_provisions sp on sp.locator=v.locator join public.regulatory_sources s on s.id=sp.regulatory_source_id and s.jurisdiction_id=rs.jurisdiction_id where rs.key='clearwater_short_term_rental_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,source_provision_id,citation_role) do nothing;
do $$ declare outcomes integer; citations integer; inputs integer; begin select count(*) into outcomes from public.rule_outcomes o join public.rule_versions rv on rv.id=o.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_short_term_rental_v1'; select count(*) into citations from public.rule_citations c join public.rule_versions rv on rv.id=c.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_short_term_rental_v1'; select count(*) into inputs from public.rule_version_inputs i join public.rule_versions rv on rv.id=i.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_short_term_rental_v1'; if outcomes<>1 or citations<>2 or inputs<>1 then raise exception 'Clearwater STR V1 incomplete (outcomes %, citations %, inputs %)',outcomes,citations,inputs; end if; end $$;
update public.rule_versions rv set lifecycle_status='active',published_at=timestamptz '2026-08-27 00:00:00+00' from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rv.rule_id=r.id and rs.key='clearwater_short_term_rental_v1' and rv.version_number=1 and rv.published_at is null;
update public.rules r set active_version_id=rv.id from public.rule_versions rv,public.rule_sets rs where rv.rule_id=r.id and rs.id=r.rule_set_id and rs.key='clearwater_short_term_rental_v1' and rv.version_number=1 and rv.lifecycle_status='active' and rv.published_at is not null;
commit;
