-- Clearwater Impervious Surface Ratio V1. Forward-only, deterministic LMDR profile.
begin;
insert into public.project_types(key,label,description) values ('impervious_surface_ratio','Impervious surface ratio','Maximum impervious surface ratio applicable to a property') on conflict(key) do nothing;
insert into public.input_definitions(key,label,description,data_type,unit_dimension,canonical_unit,value_scope,default_source_class,user_input_allowed,required_when_applicable)
values ('development.impervious_surface_ratio','Impervious surface ratio','Ratio of total impervious surface area to gross land area.','decimal','ratio','percent','global','derived',false,false) on conflict(key) do nothing;
insert into public.rule_sets(jurisdiction_id,project_type_id,key,title,scope_description,coverage_status,research_status,effective_from,verified_at,published_at,known_gaps)
select j.id,p.id,'clearwater_impervious_surface_ratio_v1','Clearwater impervious surface ratio','Deterministic LMDR maximum; both FLU designations allowed in LMDR share the same maximum.','limited','verified',date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',timestamptz '2026-08-27 00:00:00+00','["Citywide expansion requires authoritative Future Land Use and special-area-plan classification", "nonconforming and approved-plan conditions require City confirmation"]'::jsonb from public.jurisdictions j,public.project_types p where j.slug='clearwater-fl' and p.key='impervious_surface_ratio' on conflict(jurisdiction_id,project_type_id,key) do nothing;
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,v.locator,v.display,v.title,v.excerpt,'https://library.municode.com/fl/clearwater/codes/community_development_code',timestamptz '2026-08-27 00:00:00+00',v.notes from public.regulatory_sources s cross join (values
('2-201.1-isr','§ 2-201.1','LMDR maximum development potential','Residential Low and Residential Urban each have a maximum FAR .40/ISR .65.','The identical FLU results make trusted LMDR zoning sufficient for this limited profile.'),
('8-102-isr-definition','§ 8-102','Impervious and impervious surface ratio definitions','Impervious surfaces are compacted or covered surfaces highly resistant to water infiltration; ISR is total impervious surface area divided by gross land area.','Controlling definitions; examples include compacted sand, limerock, shell or clay, streets, roofs, sidewalks and parking lots.')
) v(locator,display,title,excerpt,notes) where s.title='Clearwater Community Development Code' on conflict(regulatory_source_id,locator) do nothing;
insert into public.rules(rule_set_id,key,title,group_key) select rs.id,'maximum.lmdr','LMDR maximum impervious surface ratio','maximum' from public.rule_sets rs where rs.key='clearwater_impervious_surface_ratio_v1' on conflict(rule_set_id,key) do nothing;
insert into public.rule_versions(rule_id,version_number,condition,evaluation_mode,research_status,lifecycle_status,research_confidence,summary,explanation_template,research_notes,effective_from,verified_at,published_at,schema_version)
select r.id,1,'{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'deterministic','verified','withdrawn','high','LMDR permits a maximum ISR of 0.65.','Your property allows an impervious surface ratio of up to 65%.','Section 2-201.1 assigns .65 to both FLU categories that apply within LMDR.',date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',null,1 from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_impervious_surface_ratio_v1' and r.key='maximum.lmdr' on conflict(rule_id,version_number) do nothing;
insert into public.rule_outcomes(rule_version_id,sequence,outcome_type,subject_input_id,parameters,severity,message_template)
select rv.id,1,'maximum',d.id,'{"value":65,"unit":"percent"}'::jsonb,'requirement','Your property allows an impervious surface ratio of up to 65%. This limits the share of the site covered by surfaces that resist water infiltration.' from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id join public.input_definitions d on d.key='development.impervious_surface_ratio' where rs.key='clearwater_impervious_surface_ratio_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,sequence) do nothing;
insert into public.rule_version_inputs(rule_version_id,input_definition_id,role,authority_requirement,notes)
select rv.id,d.id,'applicability','authoritative','Trusted zoning selects LMDR; its two possible FLU designations have an identical ISR maximum.' from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id join public.input_definitions d on d.key='property.zoning_district' where rs.key='clearwater_impervious_surface_ratio_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,input_definition_id,role) do nothing;
insert into public.rule_citations(rule_version_id,source_provision_id,citation_role,pinpoint_note,sequence)
select rv.id,sp.id,v.role,v.note,v.sequence from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id cross join (values ('2-201.1-isr','primary','LMDR maximum table.',1),('8-102-isr-definition','definition','Code definitions.',2)) v(locator,role,note,sequence) join public.source_provisions sp on sp.locator=v.locator join public.regulatory_sources s on s.id=sp.regulatory_source_id and s.jurisdiction_id=rs.jurisdiction_id where rs.key='clearwater_impervious_surface_ratio_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,source_provision_id,citation_role) do nothing;
do $$ declare outcomes integer; citations integer; inputs integer; begin select count(*) into outcomes from public.rule_outcomes o join public.rule_versions rv on rv.id=o.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_impervious_surface_ratio_v1'; select count(*) into citations from public.rule_citations c join public.rule_versions rv on rv.id=c.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_impervious_surface_ratio_v1'; select count(*) into inputs from public.rule_version_inputs i join public.rule_versions rv on rv.id=i.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_impervious_surface_ratio_v1'; if outcomes<>1 or citations<>2 or inputs<>1 then raise exception 'Clearwater ISR V1 incomplete (outcomes %, citations %, inputs %)',outcomes,citations,inputs; end if; end $$;
update public.rule_versions rv set lifecycle_status='active',published_at=timestamptz '2026-08-27 00:00:00+00' from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rv.rule_id=r.id and rs.key='clearwater_impervious_surface_ratio_v1' and rv.version_number=1 and rv.published_at is null;
update public.rules r set active_version_id=rv.id from public.rule_versions rv,public.rule_sets rs where rv.rule_id=r.id and rs.id=r.rule_set_id and rs.key='clearwater_impervious_surface_ratio_v1' and rv.version_number=1 and rv.lifecycle_status='active' and rv.published_at is not null;
commit;
