-- Clearwater Setbacks V1. Forward-only addition using the generalized rule schema.
begin;
insert into public.project_types(key,label,description) values ('setbacks','Setbacks','Standard residential zoning setback guidance') on conflict(key) do nothing;
insert into public.rule_sets(jurisdiction_id,project_type_id,key,title,scope_description,coverage_status,research_status,effective_from,verified_at,published_at,known_gaps)
select j.id,p.id,'clearwater_setbacks_v1','Clearwater standard residential setbacks','LMDR detached-dwelling minimum zoning setbacks and concise conditions that can change their application.','limited','verified',date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',timestamptz '2026-08-27 00:00:00+00','["Other zoning districts", "surveyed lot-line locations", "waterfront classification", "legal nonconformities"]'::jsonb from public.jurisdictions j,public.project_types p where j.slug='clearwater-fl' and p.key='setbacks' on conflict(jurisdiction_id,project_type_id,key) do nothing;
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,v.locator,v.display,v.title,v.excerpt,'https://library.municode.com/fl/clearwater/codes/community_development_code',timestamptz '2026-08-27 00:00:00+00',v.notes from public.regulatory_sources s cross join (values
('8-102-setback','§ 8-102','Setback definitions','Setback means the required horizontal distance between a property line and a structure; front, side, and rear setbacks use the corresponding property line.','Measurement semantics.'),
('3-903','§ 3-903','Required setbacks','Structures generally may not be in a zoning-district setback; corner lots have two front and two side setbacks; qualifying double-frontage lots may use a rear setback at the nonaddressed street; pools and screened pool enclosures follow principal-use setbacks.','Subsections A, C, D, and H.')
) v(locator,display,title,excerpt,notes) where s.title='Clearwater Community Development Code' on conflict(regulatory_source_id,locator) do nothing;
insert into public.rules(rule_set_id,key,title,group_key) select rs.id,v.key,v.title,v.group_key from public.rule_sets rs cross join (values
('standard.lmdr_detached_dwelling','LMDR detached-dwelling minimum setbacks','standard'),('situation.corner_multiple_frontage','Corner and multiple-frontage lots','situations'),('situation.project_specific','Project-specific setback regimes','situations'),('situation.waterfront','Waterfront rear setback','situations')) v(key,title,group_key) where rs.key='clearwater_setbacks_v1' on conflict(rule_set_id,key) do nothing;
insert into public.rule_versions(rule_id,version_number,condition,evaluation_mode,research_status,lifecycle_status,research_confidence,summary,explanation_template,research_notes,effective_from,verified_at,published_at,schema_version)
select r.id,1,v.condition,'deterministic','verified','withdrawn','high',v.summary,v.summary,v.notes,date '2024-06-06',timestamptz '2026-08-27 00:00:00+00',null,1 from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join (values
('standard.lmdr_detached_dwelling','{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'LMDR detached dwellings have minimum setbacks of 25 feet front, five feet side, and ten feet rear.','Table 2-202 applies these values to detached dwellings; it is not a universal improvement table.'),
('situation.corner_multiple_frontage','{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'Corner and qualifying double-frontage lots require different property-line treatment.','Conditional only; Groundrule does not infer lot classification.'),
('situation.project_specific','{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'Some improvements have separate rules even though structures generally must remain outside required setbacks.','Accessory structures follow district setbacks under § 3-203; pools and enclosures follow principal-use setbacks under § 3-903.H.'),
('situation.waterfront','{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,'Waterfront detached dwellings can have a different rear setback.','Conditional only; no waterfront fact is inferred.')) v(key,condition,summary,notes) on v.key=r.key where rs.key='clearwater_setbacks_v1' on conflict(rule_id,version_number) do nothing;
insert into public.rule_outcomes(rule_version_id,sequence,outcome_type,subject_input_id,parameters,severity,message_template)
select rv.id,1,v.outcome,null,v.parameters,v.severity,v.message from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id join (values
('standard.lmdr_detached_dwelling','obligation','{"front_ft":25,"side_ft":5,"rear_ft":10,"measured_from":"corresponding_property_line","measured_to":"structure","applies_to":"detached_dwelling"}'::jsonb,'requirement','Keep a detached dwelling at least 25 feet from the front property line, five feet from each side property line, and ten feet from the rear property line.'),
('situation.corner_multiple_frontage','external_authority_required','{}'::jsonb,'advisory','Corner lots have two front and two side setbacks. A qualifying double-frontage lot may treat its nonaddressed, access-restricted street side as rear. Clearwater can confirm the lot-line classification.'),
('situation.project_specific','obligation','{}'::jsonb,'advisory','Sheds, pools, additions, and other improvements must be checked under the rules for that improvement; do not treat these dwelling values as a surveyed placement approval.'),
('situation.waterfront','external_authority_required','{}'::jsonb,'advisory','The ordinary 10 ft rear value is not a waterfront answer. LMDR waterfront detached dwellings generally use 25 ft, with code and Building Code conditions that can alter the result.')) v(key,outcome,parameters,severity,message) on v.key=r.key where rs.key='clearwater_setbacks_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,sequence) do nothing;
insert into public.rule_version_inputs(rule_version_id,input_definition_id,role,authority_requirement,notes)
select rv.id,d.id,'applicability','authoritative','Trusted property zoning selects the supported district.' from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id and rv.version_number=1 join public.input_definitions d on d.key='property.zoning_district' where rs.key='clearwater_setbacks_v1' and rv.published_at is null on conflict(rule_version_id,input_definition_id,role) do nothing;
insert into public.rule_citations(rule_version_id,source_provision_id,citation_role,pinpoint_note,sequence)
select rv.id,sp.id,'primary',v.note,v.sequence from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id join (values
('standard.lmdr_detached_dwelling','2-202','Detached Dwellings row.',1),('standard.lmdr_detached_dwelling','8-102-setback','Measurement definitions.',2),('situation.corner_multiple_frontage','3-903','Subsections C and D.',1),('situation.project_specific','3-903','Subsections A and H.',1),('situation.waterfront','2-202','Detached Dwellings footnote 1.',1)) v(key,locator,note,sequence) on v.key=r.key join public.source_provisions sp on sp.locator=v.locator join public.regulatory_sources s on s.id=sp.regulatory_source_id and s.jurisdiction_id=rs.jurisdiction_id where rs.key='clearwater_setbacks_v1' and rv.version_number=1 and rv.published_at is null on conflict(rule_version_id,source_provision_id,citation_role) do nothing;
do $$ declare versions integer; outcomes integer; citations integer; inputs integer; begin
select count(*) into versions from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_setbacks_v1';
select count(*) into outcomes from public.rule_outcomes o join public.rule_versions rv on rv.id=o.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_setbacks_v1';
select count(*) into citations from public.rule_citations c join public.rule_versions rv on rv.id=c.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_setbacks_v1';
select count(*) into inputs from public.rule_version_inputs i join public.rule_versions rv on rv.id=i.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_setbacks_v1';
if versions<>4 or outcomes<>4 or citations<>5 or inputs<>4 then raise exception 'Clearwater Setbacks V1 incomplete (versions %, outcomes %, citations %, inputs %)',versions,outcomes,citations,inputs; end if; end $$;
update public.rule_versions rv set lifecycle_status='active',published_at=timestamptz '2026-08-27 00:00:00+00' from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rv.rule_id=r.id and rs.key='clearwater_setbacks_v1' and rv.version_number=1 and rv.published_at is null;
update public.rules r set active_version_id=rv.id from public.rule_versions rv,public.rule_sets rs where rv.rule_id=r.id and rs.id=r.rule_set_id and rs.key='clearwater_setbacks_v1' and rv.version_number=1 and rv.lifecycle_status='active' and rv.published_at is not null and r.active_version_id is distinct from rv.id;
commit;
