-- Clearwater Pool V1. Forward-only generalized rule package.
begin;
insert into public.project_types(key,label,description) values('pool','Pool','Residential pool placement and permit guidance') on conflict(key) do nothing;
insert into public.rule_sets(jurisdiction_id,project_type_id,key,title,scope_description,coverage_status,research_status,effective_from,verified_at,published_at,known_gaps)
select j.id,p.id,'clearwater_pool_v1','Clearwater residential pool guide','Ordinary LMDR detached-dwelling pool setbacks, measurement, review situations, and permit pathway.','limited','verified',date '2026-09-02',now(),now(),'["principal use outside detached dwelling","waterfront and flood GIS","surveyed geometry","easements"]'::jsonb from public.jurisdictions j,public.project_types p where j.slug='clearwater-fl' and p.key='pool' on conflict(jurisdiction_id,project_type_id,key) do nothing;
insert into public.regulatory_sources(jurisdiction_id,source_type,title,issuing_body,edition_label,verified_at,notes,source_metadata)
select j.id,v.type,v.title,v.body,v.edition,now(),v.notes,v.metadata from public.jurisdictions j cross join(values
('policy','Residential In-Ground Pools/Spas & Enclosures Application Checklists','City of Clearwater Planning & Development','Verified 2026-09-02','Official current permit checklist.','{"provenance":"official_city_web"}'::jsonb),
('other','Clearwater planner validation — pool measurement and waterfront review','City of Clearwater planner contact','Abi operational guidance — 2026-09-02','Operational interpretations; not represented as Code text.','{"provenance":"planner_validated","contact":"Abi","published_web_source":false}'::jsonb))v(type,title,body,edition,notes,metadata) where j.slug='clearwater-fl' on conflict do nothing;
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,v.locator,v.display,v.title,v.excerpt,v.url,now(),v.notes from public.regulatory_sources s cross join(values
('pool-checklist','City pool permit checklist','Residential pool/spa checklist','Applications require plans, safety form, Duke Energy no-conflict letter, ISR worksheet and City review.','https://www.myclearwater.com/Business-Development/Permitting/05-Residential-In-Ground-PoolsSpas-Enclosures-Application-Checklists','Official next step.'),
('pool-enclosure-checklist','City enclosure checklist','Screen/pool enclosure checklist','Applications require a current survey showing exact pool location and engineering drawings.','https://www.myclearwater.com/Business-Development/Permitting/05-Residential-In-Ground-PoolsSpas-Enclosures-Application-Checklists','Supports geometry review limitation.'))v(locator,display,title,excerpt,url,notes) where s.title='Residential In-Ground Pools/Spas & Enclosures Application Checklists' on conflict(regulatory_source_id,locator) do nothing;
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,'abi-pool-guidance','Planner guidance · Pool','Pool deck measurement and waterfront review','Measure pool setbacks to the pool deck, not merely the water; involve the Floodplain Administrator for waterfront pool projects.',null,now(),'Planner operational guidance, not a verbatim Code provision.' from public.regulatory_sources s where s.title='Clearwater planner validation — pool measurement and waterfront review' on conflict(regulatory_source_id,locator) do nothing;
-- Add current Code provisions not already seeded by another guide.
insert into public.source_provisions(regulatory_source_id,locator,display_locator,title,excerpt,source_url,verified_at,notes)
select s.id,v.locator,v.display,v.title,v.excerpt,'https://library.municode.com/fl/clearwater/codes/community_development_code',now(),v.notes from public.regulatory_sources s cross join(values
('3-204-h-pool','§ 3-204.H','Pool and associated deck classification','Pools and associated decks at or below 12 inches above grade are accessory structures; those above are principal structures.','Associated deck is expressly a structure.'),
('51-301-pool','§ 51.301','Flood hazard permits','Development wholly or partly in a flood hazard area requires application to the Floodplain Administrator and Building Official if applicable.','Flood status is separate from waterfront status.'),
('51-902-pool','§ 51.902','Compensatory excavation','Certain development outside floodways requires compensatory excavation supported by engineering analysis, subject to administrator waiver.','No calculation by Groundrule.'))v(locator,display,title,excerpt,notes) where s.title='Clearwater Community Development Code' on conflict(regulatory_source_id,locator) do nothing;
insert into public.rules(rule_set_id,key,title,group_key) select rs.id,v.key,v.title,v.grp from public.rule_sets rs cross join(values
('placement.lmdr_detached_pool','LMDR detached-dwelling pool setbacks','placement'),('placement.deck_measurement','Associated deck measurement','placement'),('placement.screen_enclosure','Screen enclosure setback','placement'),('situation.waterfront_floodplain','Waterfront and floodplain review','situations'),('situation.compensatory_excavation','Compensatory excavation','situations'),('situation.easement_utility','Easements and utility clearance','situations'),('situation.barrier','Pool barrier','situations'),('permit.checklist','Official pool permit checklist','permit'))v(key,title,grp) where rs.key='clearwater_pool_v1' on conflict(rule_set_id,key) do nothing;
insert into public.rule_versions(rule_id,version_number,condition,evaluation_mode,research_status,lifecycle_status,research_confidence,summary,explanation_template,research_notes,effective_from,verified_at,published_at,schema_version)
select r.id,1,'{"fact":"property.zoning_district","op":"eq","value":"lmdr"}'::jsonb,v.mode,'verified','withdrawn',v.conf,v.summary,v.summary,v.notes,date '2026-09-02',now(),null,1 from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join(values
('placement.lmdr_detached_pool','deterministic','high','An LMDR pool accessory to a detached dwelling uses the principal-use 25/5/10 setbacks.','Limited to detached-dwelling principal use; zoning alone does not prove use.'),
('placement.deck_measurement','informational','high','Measure to the associated pool deck, not merely the water.','Code structure chain plus planner operational interpretation.'),
('placement.screen_enclosure','informational','high','A screened pool enclosure independently meets the principal-use setbacks.','Actual closest edge requires survey and plans.'),
('situation.waterfront_floodplain','informational','high','Waterfront and mapped flood-hazard conditions require separate review.','Do not infer or conflate these facts.'),
('situation.compensatory_excavation','informational','high','Flood-related development may require technical compensatory-excavation review.','No calculation.'),
('situation.easement_utility','informational','high','Zoning setbacks do not provide easement or utility clearance.','Checklist requires Duke Energy no-conflict letter.'),
('situation.barrier','informational','high','Pools have separate safety-barrier requirements.','Fence guide is not complete pool-safety approval.'),
('permit.checklist','informational','high','Use Clearwater’s official residential pool checklist before applying.','Verified City pathway.'))v(key,mode,conf,summary,notes) on v.key=r.key where rs.key='clearwater_pool_v1' on conflict(rule_id,version_number) do nothing;
insert into public.rule_outcomes(rule_version_id,sequence,outcome_type,subject_input_id,parameters,severity,message_template)
select rv.id,1,v.type,null,v.params,v.severity,v.message from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id join(values
('placement.lmdr_detached_pool','obligation','{"front_ft":25,"side_ft":5,"rear_ft":10,"applies_to":"pool_accessory_to_detached_dwelling"}'::jsonb,'requirement','Keep the pool, associated deck, and screened enclosure outside the applicable minimum setbacks.'),
('placement.deck_measurement','obligation','{"measured_from":"corresponding_property_line","measured_to":"closest_associated_deck_edge","authority":"code_plus_planner_interpretation"}'::jsonb,'requirement','The pool and its associated deck must stay outside the required setback. A screened enclosure must also meet the applicable setback.'),
('placement.screen_enclosure','external_authority_required','{"proposed_geometry_required":true}'::jsonb,'advisory','The enclosure can be the closest project element. Clearwater requires a survey showing the pool location and engineering drawings; Groundrule does not approve the layout.'),
('situation.waterfront_floodplain','external_authority_required','{"waterfront_is_not_flood_hazard":true}'::jsonb,'warning','Waterfront property? Contact Clearwater’s Floodplain Administrator before relying on the ordinary setback result. Development in a mapped flood hazard area separately requires floodplain review.'),
('situation.compensatory_excavation','external_authority_required','{"calculation_provided":false}'::jsonb,'advisory','Certain flood-related site work may require compensatory excavation and engineering review. Groundrule does not calculate it.'),
('situation.easement_utility','external_authority_required','{"no_conflict_letter_required":true}'::jsonb,'advisory','Meeting a zoning setback does not authorize construction in an easement or establish utility clearance. The City checklist requires a Duke Energy No Conflict Letter.'),
('situation.barrier','external_authority_required','{"complete_barrier_review":false}'::jsonb,'advisory','Pools have separate safety-barrier requirements. The Fence Guide can help with Clearwater fence rules, but it is not complete pool-safety approval.'),
('permit.checklist','external_authority_required','{"official_url":"https://www.myclearwater.com/Business-Development/Permitting/05-Residential-In-Ground-PoolsSpas-Enclosures-Application-Checklists"}'::jsonb,'requirement','Review the City checklist for plans, forms, ISR worksheet, utility clearance, submission, and staff review.'))v(key,type,params,severity,message) on v.key=r.key where rs.key='clearwater_pool_v1' and rv.published_at is null on conflict(rule_version_id,sequence) do nothing;
insert into public.rule_version_inputs(rule_version_id,input_definition_id,role,authority_requirement,notes) select rv.id,d.id,'applicability','authoritative','Trusted zoning selects limited LMDR coverage; detached-dwelling use remains an explicit presentation assumption.' from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id join public.input_definitions d on d.key='property.zoning_district' where rs.key='clearwater_pool_v1' and rv.published_at is null on conflict(rule_version_id,input_definition_id,role) do nothing;
-- Every rule retains at least one receipt; deck carries Code and planner receipts separately.
insert into public.rule_citations(rule_version_id,source_provision_id,citation_role,pinpoint_note,sequence)
select rv.id,sp.id,v.role,v.note,v.seq from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id join public.rule_versions rv on rv.rule_id=r.id join(values
('placement.lmdr_detached_pool','2-202','primary','LMDR detached-dwelling row.',1),('placement.lmdr_detached_pool','3-903','primary','Subsection H incorporates principal-use setbacks.',2),
('placement.deck_measurement','3-204-h-pool','primary','Associated deck structure classification.',1),('placement.deck_measurement','abi-pool-guidance','external_dependency','Planner operational measurement guidance; not Code text.',2),
('placement.screen_enclosure','3-903','primary','Subsection H.',1),('placement.screen_enclosure','pool-enclosure-checklist','external_dependency','Survey and engineering submission.',2),
('situation.waterfront_floodplain','51-301-pool','primary','Mapped flood hazard review.',1),('situation.waterfront_floodplain','abi-pool-guidance','external_dependency','Separate waterfront operational handoff.',2),
('situation.compensatory_excavation','51-902-pool','primary','Conditional technical requirement.',1),('situation.easement_utility','pool-checklist','external_dependency','No Conflict Letter.',1),('situation.barrier','pool-checklist','external_dependency','Safety Act form.',1),('permit.checklist','pool-checklist','primary','Official resident pathway.',1))v(key,locator,role,note,seq) on v.key=r.key join public.source_provisions sp on sp.locator=v.locator join public.regulatory_sources s on s.id=sp.regulatory_source_id and s.jurisdiction_id=rs.jurisdiction_id where rs.key='clearwater_pool_v1' and rv.published_at is null on conflict(rule_version_id,source_provision_id,citation_role) do nothing;
do $$ declare v int;o int;i int;c int;begin select count(*) into v from public.rule_versions rv join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_pool_v1';select count(*) into o from public.rule_outcomes x join public.rule_versions rv on rv.id=x.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_pool_v1';select count(*) into i from public.rule_version_inputs x join public.rule_versions rv on rv.id=x.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_pool_v1';select count(*) into c from public.rule_citations x join public.rule_versions rv on rv.id=x.rule_version_id join public.rules r on r.id=rv.rule_id join public.rule_sets rs on rs.id=r.rule_set_id where rs.key='clearwater_pool_v1';if v<>8 or o<>8 or i<>8 or c<>12 then raise exception 'Pool V1 incomplete %, %, %, %',v,o,i,c;end if;end$$;
update public.rule_versions rv set lifecycle_status='active',published_at=now() from public.rules r join public.rule_sets rs on rs.id=r.rule_set_id where rv.rule_id=r.id and rs.key='clearwater_pool_v1' and rv.published_at is null;
update public.rules r set active_version_id=rv.id from public.rule_versions rv,public.rule_sets rs where rv.rule_id=r.id and rs.id=r.rule_set_id and rs.key='clearwater_pool_v1' and rv.lifecycle_status='active';
commit;
